version: "22"
checks:
  argument-count:
    config:
      threshold: 6
  method-complexity:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 100
  return-statements:
    config:
      threshold: 8
  similar-code:
    enabled: false
  identical-code:
    config:
      threshold: 100
engines:
  csslint:
    enabled: true
    checks:
      unique-headings:
        enabled: false
      qualified-headings:
        enabled: false
      box-model:
        enabled: false
      ids:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "phpcs.xml"
  phpmd:
    enabled: true
    config:
      rulesets: "phpmd.xml"
  stylelint:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.php"
