variables:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

cache:
  paths:
    - node_modules/
    - vendor/

.test:
  stage: test
  services:
    - name: mariadb:latest
      alias: mysql
  before_script:
    - bash ci/docker_install.sh > /dev/null
    - php composer.phar install
  script:
    - php composer.phar ci

php71:
  extends: .test
  image: php:7.1

php72:
  extends: .test
  image: php:7.2

php73:
  extends: .test
  image: php:7.3
  allow_failure: true

pages:
  stage: deploy
  image: node
  before_script:
    - npm install
  script:
    - ./deploy.sh
  after_script:
    - cp -r node_modules/swagger-ui-dist public
  artifacts:
    paths:
      - public
  only:
    - master
