language: php
php:
  - "7.1"
  - "7.2"
  - nightly
script:
  - composer ci
  - ./deploy.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local-dir: swagger-ui/dist
  on:
    branch: master
notifications:
  email: false
