language: php
php:
  - "7.1"
  - "7.2"
cache:
  - npm
  - directories:
    - $HOME/.composer/cache/files
before_script:
  - composer install
script:
  - composer ci
before_deploy:
  - ./deploy.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local-dir: node_modules/swagger-ui-dist
  on:
    branch: master
notifications:
  email: false
